export const GET_HOTEL_DETAIL = "GET_HOTEL_DETAIL";
export const GET_ALL_REVIEWS_OF_HOTEL = "GET_ALL_REVIEWS_OF_HOTEL";
export const GET_HOTELS_NEAR_BY = "GET_HOTELS_NEAR_BY";

export const GET_TOUR_DETAIL = "GET_TOUR_DETAIL";
export const GET_ALL_REVIEWS_OF_TOUR = "GET_ALL_REVIEWS_OF_TOUR";
export const GET_TOUR_SIMILAR = "GET_TOUR_SIMILAR";
export const AVAILABLE_ROOMS = "AVAILABLE_ROOMS";
export const CREATE_REVIEW_HOTEL = "CREATE_REVIEW_HOTEL";
export const CREATE_REVIEW_HOTEL_FAILED = "CREATE_REVIEW_HOTEL_FAILED";
export const CREATE_REVIEW_TOUR = "CREATE_REVIEW_TOUR";
export const CREATE_REVIEW_TOUR_FAILED = "CREATE_REVIEW_TOUR_FAILED";
export const BOOKING_TOUR = "BOOKING_TOUR";
export const BOOKING_ROOM = "BOOKING_ROOM";
export const BOOKING_FLIGHT = "BOOKING_FLIGHT";
