export const GET_LIST_BOOKING_HISTORY = "GET_LIST_BOOKING_HISTORY" ;
export const GET_LIST_REVIEW = "GET_LIST_REVIEW" ;
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS" ;
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED" ;
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS" ;
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED" ;