FROM node as builder

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install

COPY ./ ./

EXPOSE 5000

CMD yarn build && yarn dev

# # production environment
# FROM nginx
# COPY --from=builder /usr/src/app/build /usr/share/nginx/html
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]