export const GET_TOP_DESTINATIONS = "GET_TOP_DESTINATIONS";
export const GET_TOP_TOURS = "GET_TOP_TOURS";
export const GET_TOP_HOTELS = "GET_TOP_HOTELS";
export const GET_HOTELS = "GET_HOTELS";
export const GET_TOURS = "GET_TOURS";
export const GET_AIRPORTS = "GET_AIRPORTS";
export const POST_SELECTED_AIRPORT_START = "POST_SELECTED_AIRPORT_START";
export const POST_SELECTED_AIRPORT_END = "POST_SELECTED_AIRPORT_END";
export const POST_DATE_START_FLIGHT = "POST_DATE_START_FLIGHT";
export const POST_DESTINATION_HOTEL = "POST_DESTINATION_HOTEL";
export const POST_DESTINATION_TOUR = "POST_DESTINATION_TOUR";
export const POST_DATE_TOUR = "POST_DATE_TOUR";
export const POST_DATE_HOTEL = "POST_DATE_HOTEL";
export const POST_PRICE_HOTEL = "POST_PRICE_HOTEL";
export const POST_PRICE_TOUR = "POST_PRICE_TOUR";


